export const actionTypes = {

  //DATOS CALCULADOR PRIMERA PARTE
  GET_DATOS_CALCULADOR_PRINCIPAL: "GET_DATOS_CALCULADOR_PRINCIPAL",
  SET_DATOS_CALCULADOR_PRINCIPAL: "SET_DATOS_CALCULADOR_PRINCIPAL",
  GET_INMOBILIARIAS: 'GET_INMOBILIARIAS',
  FILTER_INMOBILIARIAS: 'FILTER_INMOBILIARIAS',
  SET_CALCULADOR: 'SET_CALCULADOR',
  SET_RESULTADO_CALCULADOR: 'SET_RESULTADO_CALCULADOR',
}